version: '3'
services:
  shairport-sync:
    container_name: shairport-sync
    restart: always
    build:
      context: .
      args:
        SHAIRPORT_VER: 3.3.2
    network_mode: host
    devices:
      - '/dev/snd'
    environment:
      - AIRPLAY_NAME=@_@
    volumes:
      - './shairport-sync.conf:/etc/shairport-sync.conf'
    image: 'xmflsct/shairport-sync:3.3.2'
