version: '3'
services:
  shairport-sync:
    container_name: shairport-sync
    restart: always
    build:
      context: .
      args:
        SHAIRPORT_VER: 3.3.4
    network_mode: host
    devices:
      - '/dev/snd'
    environment:
      - AIRPLAY_NAME=@_@
    image: 'xmflsct/shairport-sync:3.3.4'
