version: '3'
services:
  shairport-sync:
    container_name: shairport-sync
    restart: always
    network_mode: host
    devices:
      - /dev/snd
    environment:
      - AIRPLAY_NAME=@_@
    volumes:
      - ./data/shairport-sync.conf:/shairport-sync.conf
    build:
      context: .
    image: xmflsct/shairport-sync:3.3.6
